root: true

plugins:
  - '@typescript-eslint'

env:
  node: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:@typescript-eslint/strict
  - plugin:import/recommended
  - plugin:import/typescript
  - prettier
  - ./.eslintrc.rules.yml

settings:
  import/parsers:
    '@typescript-eslint/parser': ['.ts']

  import/resolver:
    node: true
    typescript:
      project:
        - ./tsconfig.json
        - ./src/tsconfig.json
        - ./test/tsconfig.json

parserOptions:
  project:
    - ./tsconfig.json
    - ./src/tsconfig.json
    - ./test/tsconfig.json

overrides:
  - files: ['src/**/*.test.ts', 'test/**/*.ts']
    plugins: [jest]
    extends: ['plugin:jest/recommended']
    rules:
      '@typescript-eslint/no-non-null-assertion': off
